

export const secrets = {
	AppKey: 'vtexappkey-dimacocl-kspwbw',
	AppToken : 'STCPCLOMRIAYUVMGCNHMKVSLCLYSGVPZGTXTDDPGOAWCOBLWBJPNMCNBQGLOVVBIMLYZMEITVRLVQCLRVKEBNHGVGDYSIZZTIRRRNIQCWXLPKDQWIBJNFAWQFZWWGOGR'
}