query product($slug: String){
    product(slug:$slug) @context(provider: "vtex.search-graphql") {
        items{
            itemId
            sellers{
                commertialOffer{
                    Price
                    ListPrice
                }
            }
        }
    }
}